# Generated by Django 3.2.3 on 2021-05-31 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PFES6', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classsubject',
            name='codeClasse',
            field=models.CharField(max_length=10),
        ),
    ]
