# Generated by Django 3.2.3 on 2021-06-02 22:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PFES6', '0004_auto_20210601_1612'),
        ('PFES6', '0005_rename_courseid_todo_course'),
    ]

    operations = [
    ]
